#!/usr/bin/env python

import os, sys

def main(args):
    n = 5
    for filename in os.listdir('.'):
        if os.path.isfile(filename):
            with open(filename, 'r') as infile:
                print('=' * 80)
                print(filename)
                print('=' * 80)
                print('\n'.join([line for line in infile][:n]))

if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
