#!/usr/bin/env python

import os, sys

def main(args):
    assert len(args) > 0, 'Must have at least one argument'
    accum = 0 
    for filename in args:
        if os.path.isfile(filename):
            with open(filename, 'r') as infile:
                accum += infile.read().count('\n')
    print(accum)

if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
